spring:
  application:
    name: eureka

logging:
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7901/eureka/,http://localhost:7902/eureka/,http://localhost:7903/eureka/
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: 7901
server:
  port: 7901
eureka:
  instance:
    hostname: localhost
---
spring:
  profiles: 7902
server:
  port: 7902
eureka:
  instance:
    hostname: localhost
---
spring:
  profiles: 7903
server:
  port: 7903
eureka:
  instance:
    hostname: localhost
